Make dependency-checking more lightweight
No need to call Class.forName. If users are missing dependencies, they
will receive a big fat NoClassDefFoundError anyway.